name 'apache'
maintainer 'JM'
maintainer_email 'jm@example.com'
license 'all_rights'
description 'Instala y arranca un servidor Apache'
long_description 'Instala y arranca un servidor Apache'
version '0.2.1'
